dll/ExportSamplesControl.xaml, dll/ViewControl.xaml, dll/ViewHandler.cs
=> Fixed issue that prevented to add spaces in the rename box  (issue #2)

.gitignore, dll/ViewHandler.cs
so hit w or a and edit details without even looking for it
=> AnnoSegment is now also selected when annotation is selected in annlistview

dll/AnnoList.cs, dll/AnnoTrack.cs, dll/AnnoTrackControl.xaml.cs, dll/Database/DatabaseAnnoScheme.xaml, dll/Database/DatabaseAnnoScheme.xaml.cs, dll/Database/DatabaseHandler.cs, dll/Database/DatabaseUserTableWindow.xaml.cs, dll/ViewHandler.cs
For Annotations in the Database following a non-restrictive
AnnotaionScheme (e.g. for allowing Text Transcriptions, and other "free"
labeling tasks. Preparations for new File format coming soon.
=> added Annotations of type "Free"

app/Window1.xaml, dll/AnnoList.cs, dll/AnnoTrack.cs, dll/AnnoTrackSegment.cs, dll/Database/DatabaseHandler.cs, dll/LabelInputBox.xaml.cs, dll/NavigatorControl.xaml, dll/PatternBrushes.xaml, dll/PatternBrushes.xaml.cs, dll/Properties/Settings.Designer.cs, dll/Properties/Settings.settings, dll/Settings.xaml, dll/Settings.xaml.cs, dll/TrackControl.xaml, dll/ViewControl.xaml, dll/ViewHandler.cs, dll/app.config, dll/viewdll.csproj
Added a new mode that allows to correct labels with low confidence (e.g.
automated labels, created by a classifier, or labels that need rework in
general). Minor bugfixes
=> Correction Mode + Bugfixes

.gitignore, app/nova.csproj, dll/Properties/Settings.Designer.cs, dll/Properties/Settings.settings, dll/Settings.xaml, dll/Settings.xaml.cs, dll/ViewHandler.cs, dll/app.config
=> added option to set default zoom (0 for max length)

dll/AnnoList.cs, dll/Database/DatabaseHandler.cs
(both for files and for Database)
=> Added default GARBAGE class to Annotation Schemes

dll/AnnoTrack.cs, dll/AnnoTrackSegment.cs, dll/ViewControl.xaml, dll/ViewHandler.cs
the minduration option did trigger so far for new sections. Now also
triggers when editing an existing section
=> minor bug fix for new segments minduration option

dll/AnnoList.cs, dll/Database/DatabaseFunctions.xaml, dll/Database/DatabaseFunctions.xaml.cs, dll/Database/DatabaseHandler.cs, dll/Database/DatabaseHandlerWindow.xaml, dll/Database/DatabaseHandlerWindow.xaml.cs, dll/ViewHandler.cs
=> The Database Window now shows the annotators name

dll/Properties/Settings.Designer.cs, dll/Properties/Settings.settings, dll/ViewHandler.cs, dll/app.config
use 0-9 on discrete tiers to quickly change annotations (0 is always
Garbage)
=> added hotkeys

dll/AnnoListControl.xaml, dll/AnnoListControl.xaml.cs, dll/AnnoTrack.cs, dll/Database/DatabaseHandlerWindow.xaml.cs, dll/ViewHandler.cs
or 1.
- Fixed loading of mutliple files from database *fingerscrossed
=> added context menu to set all confidences to 0

dll/MediaKit.cs
- fixed a  bug that kept media codec opened in background
=> changed default unload behaviour for media

app/Window1.xaml, app_metro/Window1.xaml, dll/AnnoTrack.cs, dll/AnnoTrackSegment.cs, dll/Database/DatabaseHandler.cs, dll/Database/DatabaseHandlerWindow.xaml, dll/Database/DatabaseHandlerWindow.xaml.cs, dll/ViewHandler.cs
New Shortcuts:
- t + arrow up/down: select last/next tier
- alt + arrow up/down: when segment is selected created a new one with
the same length on last/next tier
- Relabel multiple scores on a continuous tier by selecting an are
(shift + right click to select an area), select area and hit W (just
like for discrete annotations) and change value / confidence for area
- multi copy/delete in admin interface
=> new shortcuts

dll/ViewHandler.cs
=> added shift + ctrl + s to mark as finished in db

app/Window1.xaml, app_metro/Window1.xaml, dll/AnnoSchemeEditor.xaml, dll/AnnoSchemeEditor.xaml.cs, dll/AnnoTrack.cs, dll/Properties/Settings.Designer.cs, dll/Properties/Settings.settings, dll/Settings.xaml, dll/Settings.xaml.cs, dll/ViewHandler.cs, dll/app.config
A new option is now available in the settings to set a fixed samplerate
to a discrete tier. (Default 25 fps). If it's set to 0 it will have
default behaviour, elsewise it will snap to the samplerate.  Ctrl  + R
adjusts existing labels to the sample rate
=> added samplerate for discrete labels

app/Window1.xaml.cs, app/nova.csproj, dll/AnnoList.cs, dll/AnnoSchemeEditor.xaml.cs, dll/AnnoTrack.cs, dll/SignalStatsWindow.xaml, dll/SignalStatsWindow.xaml.cs, dll/SignalTrackEx.xaml, dll/SignalTrackEx.xaml.cs, dll/ViewHandler.cs, dll/ViewTime.cs, dll/viewdll.csproj
- added first version of statistics
- fixed an issue with discrete samplerate
- added  annoscheme editor
=> weekend updates

Controls/MainControl.xaml, Controls/MainHandler.cs, Controls/MainHandlerMenu.cs, Database/DatabaseAdminManageDBWindow.xaml.cs, Database/DatabaseAdminManageSessionsWindow.xaml.cs, Database/DatabaseHandler.cs
databases were not shown to users who are not an admin
=> Fixed a bug related to user rights on databases

Controls/MainHandler.cs, Controls/MainHandlerDatabase.cs, Controls/MainHandlerFile.cs, Database/DatabaseAdminManageAnnotationsWindow.xaml.cs, Database/DatabaseAdminManageDBWindow.xaml.cs, Database/DatabaseAdminManageSessionsWindow.xaml.cs, Database/DatabaseAdminStreamWindow.xaml.cs, Database/DatabaseAnnoMainWindow.xaml, Database/DatabaseAnnoMainWindow.xaml.cs, Database/DatabaseAnnoMergeWindow.xaml.cs, Database/DatabaseCMLExtractFeaturesWindow.xaml.cs, Database/DatabaseCMLTrainAndPredictWindow.xaml.cs, Database/DatabaseHandler.cs, Properties/Settings.Designer.cs, Properties/Settings.settings, Types/AnnoList.cs, Types/AnnoSource.cs, Types/Face.cs, app.config
- new internal Database storage format (split data from meta)
- references are solved only once a database is selected, not every time
- minor fixes/improvements
=> Speed up database usage

Controls/MainHandler.cs, Database/DatabaseCMLTrainAndPredictWindow.xaml, Database/DatabaseCMLTrainAndPredictWindow.xaml.cs, Tools/Defaults.cs
Add .set files to the main folder of a database to quickly select a train or eval set. set files contain one folder per line.
=> support for Sets

Controls/Annotation/AnnoTier.cs, Controls/MainHandler.cs, Controls/MainHandlerFile.cs, Controls/MainHandlerKey.cs
Allows L + W Key combination to create labels without mouse
=> use L Key for segments to move green cursor

Controls/MainHandler.cs, Controls/MainHandlerFile.cs, Controls/Other/Settings.xaml, Controls/Other/Settings.xaml.cs, Properties/Settings.Designer.cs, Properties/Settings.settings, app.config
(In case you have a slow network connection or harddrive, this will save a lot of time loading, but the wavform is not shown when checked)
=> added option to deactivate waveform from videofiles

Controls/MainHandlerDownload.cs
fixed python 3.8.10 download path
=> fixed python download path

.gitignore, Controls/Annotation/AnnoTier.cs, Controls/Annotation/AnnoTierNewLabelWindow.xaml, Controls/Annotation/AnnoTierNewLabelWindow.xaml.cs, Controls/MainHandler.cs, Controls/MainHandlerKey.cs, Controls/MainHandlerNavigation.cs
d for context independent new label (previous selection is unselected)
j for select label the time cursor is above
u to unselect current label
=> added new navigation buttons, d, j and u, for keyboard only annotation.

Controls/Annotation/AnnoTier.cs, Controls/MainHandlerFile.cs, Database/DatabaseHandler.cs, Types/AnnoListFile.cs, Types/AnnoScheme.cs
Branch kann gemergt und geschlossen werden
=> Bug behoben, dass mehrere Videos mit Polygonanno geöffnet werden können

Controls/MainHandler.cs, Controls/MainHandlerFile.cs, Controls/Other/Settings.xaml, Controls/Other/Settings.xaml.cs, Properties/Settings.Designer.cs, Properties/Settings.settings, Types/AnnoListFile.cs, app.config
including option to pick between word and sentence level
=> added option to import SRT subtitle files as free annotations

Database/DatabaseCMLTrainAndPredictWindow.xaml, Database/DatabaseCMLTrainAndPredictWindow.xaml.cs
Branch kann danach gelöscht werden.
=> CML Startpoint hinzugefuegt

Database/DatabaseAnnoStatisticsWindow.xaml.cs
=> Statistics

README.md
Updated recommended codec packs with more security safe one, which does not include "infatica" backdoor application.
=> Update README.md (replaced recommended codec packs with safer one)
